### ISSUE TITLE
missing C optimisations

### ISSUE THREAD

**Issue by Smattr** [kmill/lean4-raytracer#1]
I'm not sure if the C benchmark here is meant to be "optimised to the hilt" or just reasonably representative. Obviously you want it to somewhat correspond to the Lean implementation, but it's possible to teach the compiler more about this code.

All the functions except `main` in render.c could be marked static. Alternatively, `-fwhole-program` has the same effect in GCC. This improves the compiler's ability (or maybe willingness) to inline and specialize functions. Link-time optimisation could also be added on top of this with `-flto` that might further accelerate it.

Maybe these comments are not relevant and you just wanted to compare against reasonably optimised C. But if not, I hope these comments are helpful.

**Comment by kmill** [comment]
Sorry, I hadn't noticed the issues on this repository until now!

This C program isn't meant to be ultra-optimized, though I wrote it with some thought toward make sure it was reasonably efficient. I'd looked through the assembly generated by the compiler (there's a Makefile target for that), and everything was actually fairly well inlined already. The main cost to raytracing seems to be the arithmetic rather than potential overhead from calling conventions.

If you want to investigate this, feel free to measure whether these suggestions have an affect and report back.
